sudo: required
dist: trusty

language:
    - c
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - valgrind
    - clang
    - gcc
    - gcc-6
    - python-docutils
    - python3-pip
install: test/travis-install.sh
script: test/travis-build.sh

